export const SET_FILM_URL = 'SET_FILM_URL';
export const SET_FILTER_BY_FILM = 'SET_FILTER_BY_FILM';
export const SET_FILTER_BY_SPECIES = 'SET_FILTER_BY_SPECIES';
export const SET_FILTER_BY_YEAR = 'SET_FILTER_BY_YEAR';
export const SET_CHARACTERS_BY_INPUT = 'SET_CHARACTERS_BY_INPUT';
export const SET_CHARACTERS_BY_FILM_OPTION = 'SET_CHARACTERS_BY_FILM_OPTION';
export const SET_CHARACTERS_BY_SPECIES_OPTION =
  'SET_CHARACTERS_BY_SPECIES_OPTION';
export const SET_CHARACTERS_BY_YEAR_OPTION = 'SET_CHARACTERS_BY_YEAR_OPTION';
export const SET_MIN_YEAR_OPTION = 'SET_MIN_YEAR_OPTION';
export const SET_MAX_YEAR_OPTION = 'SET_MAX_YEAR_OPTION';
export const SET_AND_OR_OPTION = 'SET_AND_OR_OPTION';
